from .base import BaseRequest
from enum import Enum

class VisibilityEnum(str, Enum):
    ALL = 'ALL'
    VISIBLE = "VISIBLE" 
    INVISIBLE = "INVISIBLE" 
    EMPTY_STOCK = "EMPTY_STOCK" 
    NOT_MODERATED = "NOT_MODERATED" 
    MODERATED = "MODERATED" 
    DISABLED = "DISABLED" 
    STATE_FAILED = "STATE_FAILED" 
    READY_TO_SUPPLY = "READY_TO_SUPPLY" 
    VALIDATION_STATE_PENDING = "VALIDATION_STATE_PENDING" 
    VALIDATION_STATE_FAIL = "VALIDATION_STATE_FAIL" 
    VALIDATION_STATE_SUCCESS = "VALIDATION_STATE_SUCCESS" 
    TO_SUPPLY = "TO_SUPPLY" 
    IN_SALE = "IN_SALE" 
    REMOVED_FROM_SALE = "REMOVED_FROM_SALE" 
    BANNED = "BANNED" 
    OVERPRICED = "OVERPRICED" 
    CRITICALLY_OVERPRICED = "CRITICALLY_OVERPRICED" 
    EMPTY_BARCODE = "EMPTY_BARCODE" 
    BARCODE_EXISTS = "BARCODE_EXISTS" 
    QUARANTINE = "QUARANTINE" 
    ARCHIVED = "ARCHIVED" 
    OVERPRICED_WITH_STOCK = "OVERPRICED_WITH_STOCK" 
    PARTIAL_APPROVED = "PARTIAL_APPROVED" 
    IMAGE_ABSENT = "IMAGE_ABSENT" 
    MODERATION_BLOCK = "MODERATION_BLOCK"

class ProductListFilterRequest(BaseRequest):
    offer_id: list[str] = ''
    product_id: list[str] = ''
    visibility: VisibilityEnum
